// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class EyesBlink : MonoBehaviour {
				
	public SpriteRenderer[] eyes;

	public Sprite OpenedEye;
	public Sprite ClosedEye;

	public float blinkDuration = .1f;
	public float blinkFrequencyMin = 2f;
	public float blinkFrequencyMax = 5f;

	private float nextBlinkTime;

	void Start() {
		nextBlinkTime = UnityEngine.Random.Range(blinkFrequencyMin, blinkFrequencyMax);
	}

	void Update() {
		nextBlinkTime -= Time.deltaTime;
		if (nextBlinkTime < 0f) {
			StartCoroutine( BlinkCoroutine() );
			nextBlinkTime = UnityEngine.Random.Range(blinkFrequencyMin, blinkFrequencyMax);
		}
	}

	private IEnumerator BlinkCoroutine() {
		SetSpritesToEyes( ClosedEye );
		yield return new WaitForSeconds( blinkDuration );
		SetSpritesToEyes( OpenedEye );
	}

	private void SetSpritesToEyes(Sprite eyeSprite) {
		foreach(SpriteRenderer eye in eyes) {
			eye.sprite = eyeSprite;
		}
	}

}

